settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
server:
  status: true
  open: true
  port: 5002
  host: localhost
schema:
- name: issa-ipsum
  path: .
  commands:
    vet:
      args:
      - none
    install:
      status: true
    run:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - html
    ignored_paths:
    - .git
    - .realize
    - vendor
